name: Scrape Cars Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-news-for-bharat:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scrapper_requirements.txt

      - name: Ensure Cars Directory Exists
        run: |
          mkdir -p ./cars

      - name: Clear Previous Files
        run: |
          rm -rf ./cars/*

      - name: Remove previously tracked files if any
        run: |
          git rm -r --cached ./cars/* || true

      - name: Scrape cars data
        run: |
          python scraper.py

      - name: Commit and Push Generated File
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S IST" --date="5 hours 30 minutes")

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git pull

          git add ./cars/
          git commit -m "Scraped cars data ($TIMESTAMP)"

          git push origin master

      - name: Confirm Completion
        run: |
          echo "Successfully scrapped all cars data"
