name: Scrape Cars Data

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  scrape-news-for-bharat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Scrape cars data
      run: |
        python scraper.py

    - name: Clear previous files
      run: |
        rm -rf ./cars/*

    - name: Commit and Push Generated File
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S IST" --date="5 hours 30 minutes")
        
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git pull

        git add ./cars/
        git commit -m "Scraped cars data ($TIMESTAMP)"

        git push origin master

    - name: Confirm Completion
      run: |
        echo "Successfully scrapped all cars data"
